# Generated by Django 5.0.7 on 2025-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('dermatology', 'Dermatology'), ('general', 'General Medicine')], max_length=50)),
                ('doctor', models.CharField(choices=[('dr-johnson', 'Dr. Sarah Johnson'), ('dr-martinez', 'Dr. Michael Martinez'), ('dr-chen', 'Dr. Lisa Chen'), ('dr-patel', 'Dr. Raj Patel'), ('dr-williams', 'Dr. Emily Williams'), ('dr-thompson', 'Dr. David Thompson')], max_length=50)),
                ('date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
