# Generated by Django 5.0.7 on 2025-11-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics'), ('General Surgery', 'General Surgery')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('available_this_week', models.BooleanField(default=True)),
                ('years_experience', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('certifications', models.CharField(blank=True, max_length=200)),
                ('residency', models.CharField(blank=True, max_length=200)),
                ('fellowship', models.CharField(blank=True, max_length=200)),
                ('publications', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
