# Generated by Django 5.0.7 on 2025-11-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_medicine_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Painkiller', 'Painkiller'), ('Antibiotic', 'Antibiotic'), ('Vitamin', 'Vitamin'), ('Antiseptic', 'Antiseptic'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
