# Generated by Django 5.0.7 on 2025-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_medicine_category_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='seller_mpesa_number',
            field=models.CharField(default=254791074671, help_text='The M-Pesa number that will receive payment for this medicine (e.g., 254712345678).', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='seller_name',
            field=models.CharField(default=254791074671, help_text='Name of the doctor or chemist selling this medicine.', max_length=100),
            preserve_default=False,
        ),
    ]
