# Generated by Django 5.0.7 on 2025-11-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_cart_session_id_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
