# Generated by Django 5.0.7 on 2025-11-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualpayment',
            name='transaction_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
