# Generated by Django 5.0.7 on 2025-11-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_testorder_vaccinationappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='use',
        ),
    ]
