# Generated by Django 5.0.7 on 2025-11-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_rename_user_cart_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='use',
            new_name='user',
        ),
    ]
