# Generated by Django 5.0.7 on 2026-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_patientrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='seller_mpesa_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='seller_name',
            field=models.CharField(max_length=100),
        ),
    ]
