from pathlib import Path
import os

# from dotenv import load_dotenv
# load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("SECRET_KEY", "unsafe-dev-key")

DEBUG = False

ALLOWED_HOSTS = [
    ".vercel.app",
    "localhost",
    "127.0.0.1"
]


# ---------------- APPS ----------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'medical',
]


# ---------------- MIDDLEWARE ----------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # IMPORTANT
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'medicinal.urls'

WSGI_APPLICATION = 'medicinal.wsgi.application'


# ---------------- DATABASE (FIXED) ----------------
# Vercel is temporary → SQLite works only for demo
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ---------------- TEMPLATES ----------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ---------------- STATIC FILES (FIXED FOR VERCEL) ----------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ---------------- SECURITY ----------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------- REMOVE CHANNELS (IMPORTANT) ----------------
# ❌ REMOVE THIS COMPLETELY:
# CHANNEL_LAYERS = {...}


# ---------------- EMAIL (SAFE FOR PROD) ----------------
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# # ---------------- ENV VARIABLES ----------------
# MPESA_CONSUMER_KEY = os.getenv("MPESA_CONSUMER_KEY")
# MPESA_CONSUMER_SECRET = os.getenv("MPESA_CONSUMER_SECRET")
# MPESA_SHORTCODE = os.getenv("MPESA_SHORTCODE", "174379")
# MPESA_PASSKEY = os.getenv("MPESA_PASSKEY")
# MPESA_CALLBACK_URL = os.getenv(
#     "MPESA_CALLBACK_URL",
#     "https://your-domain.vercel.app/mpesa/callback/"
# )

# OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


# ---------------- LOGIN ----------------
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'























# """
# Django settings for medicinal project.

# Generated by 'django-admin startproject' using Django 4.2.25.
# """

# from pathlib import Path
# import os

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECRET_KEY = 'django-insecure-ao(-0grb0&61arh6nx735x*rnb*$8%z%gstpmmv9j4o*-84f++'

# DEBUG = True

# ALLOWED_HOSTS = ['.vercel.app']


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'medical',  # your app
#     'channels',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'medicinal.urls'


# # -------------------- Templates --------------------
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         # Add your templates directory
#         'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'medicinal.wsgi.application'


# # -------------------- Database --------------------
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



# # -------------------- Password Validation --------------------
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]


# # -------------------- Internationalization --------------------
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'Africa/Nairobi'  # optional: matches your local time zone
# USE_I18N = True
# USE_TZ = True


# # -------------------- Static & Media Files --------------------
# STATIC_URL = '/static/'

# # This tells Django where to look for static files during development
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',  # project-level static folder
# ]

# # Where collected static files will be stored (used in deployment)
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# # Media (if you’ll be uploading files later)
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# # -------------------- Default Primary Key --------------------
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-email-password'
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER




# import os
# from dotenv import load_dotenv
# load_dotenv()

# MPESA_CONSUMER_KEY = os.getenv("MPESA_CONSUMER_KEY")
# MPESA_CONSUMER_SECRET = os.getenv("MPESA_CONSUMER_SECRET")
# MPESA_SHORTCODE = os.getenv("MPESA_SHORTCODE", "174379")
# MPESA_PASSKEY = os.getenv("MPESA_PASSKEY")
# MPESA_CALLBACK_URL = "https://freddy-porkiest-rumblingly.ngrok-free.dev/mpesa/callback/"





# OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# # settings.py

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }
# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = 'home'
# LOGOUT_REDIRECT_URL = 'home'  